extends Node

const MAXIMUM_MANA = 300
const INITIAL_MANA = 100
const ARCHER_COST = 10
const ARCHER_ATTACK_INTERVAL = 2
const MAGE_COST = 20
const MAGE_ATTACK_INTERVAL = 3
const DEFENDER_COST = 20
const ELDER_COST = 30
const DARK_SPREAD_INTERVAL = 10
const MAXIMUM_HEALTH = 100
const MOVE_SPEED = 300
const ZOOM_SPEED = 2
const ZOOM_MAX = 2
const ZOOM_MIN = 0.25
const PORTAL_COST = 150
const DARKNESS_DAMAGE = 25
const SPIRIT_DAMAGE = 25
