extends Node

const MAXIMUM_MANA = 300
const INITIAL_MANA = 100
const ARCHER_COST = 5
const ARCHER_ATTACK_INTERVAL = 2
const ARCHER_HEALTH = 100
const MAGE_COST = 20
const MAGE_ATTACK_INTERVAL = 3
const MAGE_HEALTH = 150
const DEFENDER_COST = 20
const ELDER_COST = 30
const DARK_SPREAD_INTERVAL = 10
const MOVE_SPEED = 50
const ZOOM_SPEED = 2
const ZOOM_MAX = 2
const ZOOM_MIN = 0.25
const PORTAL_COST = 150
const DARKNESS_DAMAGE = 25
const SPIRIT_DAMAGE = 20
const PLAYER_BONUS = 2
const ATTACK_RANGE = 2
